# Build settings for Next.js with output: "export"
[build]
  command = "npm run build"
  publish = "out"

# Environment variables (optional, ensures production mode)
[build.environment]
  NODE_ENV = "production"

# Headers configuration, including Content-Security-Policy
[[headers]]
  for = "/(.*)"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.clarity.ms https://www.google.com https://www.google-analytics.com https://messages-dump.s3.ap-south-1.amazonaws.com https://cdn.socket.io https://googleads.g.doubleclick.net https://www.google.co.in; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com data:; img-src 'self' data: https://*.clarity.ms https://www.google.com https://www.googletagmanager.com https://botwot-user-data-info.s3.ap-south-1.amazonaws.com https://googleads.g.doubleclick.net https://www.google.co.in https://www.googleadservices.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://*.clarity.ms https://uatapi.botwot.io wss://uatapi.botwot.io https://www.google.com https://googleads.g.doubleclick.net; frame-src https://td.doubleclick.net https://www.googletagmanager.com https://www.google.com https://googleads.g.doubleclick.net;"

# Cache control for static assets (recommended for performance)
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects to ensure client-side routing works for a static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200